apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minikube-web

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: minikube-web
  managed-by: argocd

images:
  - name: nginx
    newTag: alpine