apiVersion: v1
kind: Service
metadata:
  name: minikube-web-service
  namespace: minikube-web
spec:
  selector:
    app: minikube-web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: NodePort  # 使用 NodePort 在 Minikube 中访问