apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minikube-web-demo
  namespace: argocd
spec:
  project: default
  
  # Git 仓库信息
  source:
    repoURL: https://github.com/pengchao2022/argocd-minikube-demo.git
    targetRevision: HEAD
    path: manifests/
  
  # 目标集群（Minikube）
  destination:
    server: https://127.0.0.1:53599
    namespace: minikube-web
  
  # 同步策略（简化版本，避免兼容性问题）
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true